spring.application.name=mnemos
spring.data.mongodb.uri=mongodb+srv://shravanjain:xE2gO6EgZc5dc475@cluster0.plvtclx.mongodb.net/mnemos?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.auto-index-creation=true
spring.security.user.name=admin
spring.security.user.password=test123