spring.application.name=mnemos
spring.data.mongodb.uri=mongodb://localhost:27017/JournalDB
spring.data.mongodb.auto-index-creation=true
spring.security.user.name=admin
spring.security.user.password=$2a$08$GdRDloLRkDTBuJjfogFe0eASljEJd36HrQrMA5S86o7SAyTSySb1C