/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'primary': '#b9ccb7',
        'primary-dim': '#abbea9',
        'primary-container': '#3a4b3b',
        'primary-fixed': '#d5e8d2',
        'primary-fixed-dim': '#c7dac4',
        'on-primary': '#344435',
        'on-primary-container': '#c3d5c0',
        'on-primary-fixed': '#334334',
        'on-primary-fixed-variant': '#4f604f',
        'secondary': '#9d9e9a',
        'secondary-dim': '#9d9e9a',
        'secondary-container': '#393c38',
        'secondary-fixed': '#e2e3dd',
        'secondary-fixed-dim': '#d4d5d0',
        'on-secondary': '#1e211e',
        'on-secondary-container': '#bec0bb',
        'on-secondary-fixed': '#3d403c',
        'on-secondary-fixed-variant': '#5a5c58',
        'tertiary': '#e9ffed',
        'tertiary-dim': '#cdedd6',
        'tertiary-container': '#d3f3dc',
        'tertiary-fixed': '#dbfce4',
        'tertiary-fixed-dim': '#cdedd6',
        'on-tertiary': '#496553',
        'on-tertiary-container': '#415d4b',
        'on-tertiary-fixed': '#34503f',
        'on-tertiary-fixed-variant': '#506d5a',
        'surface': '#0e0e0e',
        'surface-dim': '#0e0e0e',
        'surface-bright': '#2b2c2c',
        'surface-variant': '#252626',
        'surface-tint': '#b9ccb7',
        'surface-container': '#191a1a',
        'surface-container-low': '#131313',
        'surface-container-high': '#1f2020',
        'surface-container-highest': '#252626',
        'surface-container-lowest': '#000000',
        'on-surface': '#e7e5e5',
        'on-surface-variant': '#acabaa',
        'background': '#0e0e0e',
        'on-background': '#e7e5e5',
        'outline': '#767575',
        'outline-variant': '#484848',
        'error': '#ed7f64',
        'error-dim': '#ba573f',
        'error-container': '#7e2b17',
        'on-error': '#450900',
        'on-error-container': '#ff9b82',
        'inverse-surface': '#fcf9f8',
        'inverse-on-surface': '#565555',
        'inverse-primary': '#526352',
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Newsreader', 'serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
